export const UsersLabel = {
    addUser: 'Agregar nuevo usuario',
    all: 'Todos',
    asc: 'Ordenar de A - Z',
    desc: 'Ordenar de Z - A',
    middle: 'mitad',
    option1: '8 por página',
    option2: '12 por página',
    option3: '16 por página',
    option4: '20 por página',
    preview: 'Previsualizar',
    search: 'Búsqueda',
    textTitle: 'sdofei ladwmi osdfli, eins sid lsirefj ldsi',
    title: 'Usuarios',
    photo: 'Foto',
    name: 'Nombre',
    fathersLastName: 'Apellido paterno',
    mothersLastName: 'Apellido materno',
    email:'Correo',
    roleId: 'Rol',
    active: 'Status',
    nothingRole: 'Sin rol',
};